apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: tqxpi3pqy-python
  janus-idp.io/tekton: tqxpi3pqy-python
  backstage.io/kubernetes-id: tqxpi3pqy-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: tqxpi3pqy-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
