apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: tqxpi3pqy-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: tqxpi3pqy-python 
  name: tqxpi3pqy-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: tqxpi3pqy-python 
